substitutions:
  system_name: esph_ufh_cntrl
  friendly_name: "Underfloor heating PID and PWM controller"
  device_description: "This device is designed to control underfloor heating according to a preset temperature"
  log_level: DEBUG
  pwm_gpio_pin: GPIO15
  pwm_gpio_period: 20min


esphome:
  name: ${system_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: nivanov0.underfloor_controller
    version: "0.1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key


ota: 
  password: !secret ota_key

dashboard_import:
  package_import_url: github://nivanov0/esphome_config/${system_name}.yaml@master
  import_full_config: true # or true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${system_name}"
    password: "SmdoNfqyfVN4"

captive_portal:

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

web_server:
  local: true

sensor:
  - platform: template
    name: "Template Sensor"
    id: template_sens
    update_interval: 1s

  - platform: duty_cycle
    pin: GPIO16
    name: Duty Cycle Sensor
    update_interval: 10s

  - platform: pid
    name: "PID Climate Result"
    type: RESULT

  - platform: homeassistant
    entity_id: sensor.h_t_plus_living_room_zonata_temperature
    name: "Living room temperature"
    id: living_room_temperature
    on_value:
      then:
        - sensor.template.publish:
            id: template_sens
            state: !lambda 'return id(living_room_temperature).state;'
output:
  - platform: slow_pwm
    id: my_slow_pwm
    pin: ${pwm_gpio_pin}
    period: ${pwm_gpio_period}

    
climate:
  - platform: pid
    name: "PID Climate Controller"
    id: pid_controller
    sensor: template_sens
    default_target_temperature: 24째C
    heat_output: my_slow_pwm
    control_parameters:
      kp: 1
      ki: 0
      kd: 0
    deadband_parameters:
      threshold_high: 0.5째C       # deadband within +/-0.5째C of target_temperature
      threshold_low: -0.5째C
