substitutions:
  system_name: esph-ufh-cntrl
  friendly_name: "Underfloor heating PID and PWM controller"
  device_description: "This device is designed to control underfloor heating according to a preset temperature"
  log_level: DEBUG
  pwm_gpio_pin: GPIO15
  pwm_gpio_period: 20min


esphome:
  name: ${system_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: nivanov0.underfloor_controller
    version: "0.1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  


ota: 
  

wifi:
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${system_name}"
    password: "123456789"

captive_portal:

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

web_server:
  local: true

sensor:
#This is an example temperature sensor for the PID controller. Add yours and edit sensor: template_sens in the climate section
  - platform: homeassistant
    entity_id: sensor.living_room_temperature
    name: "Living room temperature"
    id: replace_me
    
output:
  - platform: slow_pwm
    id: my_slow_pwm
    pin: ${pwm_gpio_pin}
    period: ${pwm_gpio_period}

    
climate:
  - platform: pid
    name: "PID Climate Controller"
    id: pid_controller
    sensor: replace_me
    default_target_temperature: 24째C
    heat_output: my_slow_pwm
    control_parameters:
      kp: 1
      ki: 0
      kd: 0
    deadband_parameters:
      threshold_high: 0.5째C       # deadband within +/-0.5째C of target_temperature
      threshold_low: -0.5째C
