substitutions:
  system_name: esph-ufh-cntrl
  friendly_name: "Underfloor heating PID and PWM controller"
  device_description: "This device is designed to control underfloor heating according to a preset temperature"
  log_level: DEBUG
  pwm_gpio_pin: GPIO15
  pwm_gpio_period: 20min

esphome:
  name: ${system_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: nivanov0.underfloor_controller
    version: "0.1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

ota: 

wifi:
  ap:

captive_portal:

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

web_server:
  local: true

sensor:
  - platform: template
    name: "Template Sensor"
    id: current_temperature
    internal: True
    
output:
  - platform: slow_pwm
    id: my_slow_pwm
    pin: ${pwm_gpio_pin}
    period: ${pwm_gpio_period}

number:
  - platform: template
    name: "Current Temperature"
    id: current_temperature_num
    optimistic: true
    min_value: -20
    max_value: 50
    step: 0.1
    on_value:
      then:
        - sensor.template.publish:
            id: current_temperature
            state: !lambda 'return id(current_temperature_num).state;' 
climate:
  - platform: pid
    name: "PID Climate Controller"
    id: pid_controller
    sensor: replace_me
    default_target_temperature: 24째C
    heat_output: my_slow_pwm
    control_parameters:
      kp: 1
      ki: 0
      kd: 0
    deadband_parameters:
      threshold_high: 0.5째C       # deadband within +/-0.5째C of target_temperature
      threshold_low: -0.5째C
